-- ============================================================
-- SIGEU - Sistema de Reservas de Espacios Universitarios
-- DDL - Data Definition Language
-- Motor: PostgreSQL / Supabase
-- Schema: SIGEU
-- ============================================================

-- Tabla: USER_TYPE
CREATE TABLE SIGEU.USER_TYPE (
    USERTYPE_ID  VARCHAR(2)  NOT NULL,
    NAME         VARCHAR(15) NOT NULL,
    CONSTRAINT PK_USERTYPE_ID PRIMARY KEY (USERTYPE_ID)
);

-- Tabla: USER
CREATE TABLE SIGEU.USER (
    CODE         VARCHAR(10) NOT NULL,
    NAME1        VARCHAR(30) NOT NULL,
    NAME2        VARCHAR(30),
    LAST_NAME1   VARCHAR(30) NOT NULL,
    LAST_NAME2   VARCHAR(30),
    EMAIL        VARCHAR(50) NOT NULL,
    CELLPHONE    VARCHAR(15),
    USERTYPE_ID  VARCHAR(2),
    CONSTRAINT PK_CODE PRIMARY KEY (CODE),
    CONSTRAINT FK_USERTYPE_USER FOREIGN KEY (USERTYPE_ID)
        REFERENCES SIGEU.USER_TYPE (USERTYPE_ID)
);

-- Tabla: LOCATION
CREATE TABLE SIGEU.LOCATION (
    LOCATION_ID  VARCHAR(2)   NOT NULL,
    NAME         VARCHAR(100) NOT NULL,
    CONSTRAINT PK_LOCATION_ID PRIMARY KEY (LOCATION_ID)
);

-- Tabla: BUILDING
CREATE TABLE SIGEU.BUILDING (
    BUILDING_ID  VARCHAR(2)  NOT NULL,
    NAME         VARCHAR(50) NOT NULL,
    LOCATION_ID  VARCHAR(2)  NOT NULL,
    CONSTRAINT PK_BUILDING_ID PRIMARY KEY (BUILDING_ID),
    CONSTRAINT FK_LOCATION_BUILDING FOREIGN KEY (LOCATION_ID)
        REFERENCES SIGEU.LOCATION (LOCATION_ID)
);

-- Tabla: SPACE_TYPE
CREATE TABLE SIGEU.SPACE_TYPE (
    SPACE_TYPE_ID  VARCHAR(2)  NOT NULL,
    NAME           VARCHAR(30) NOT NULL,
    CONSTRAINT PK_SPACE_TYPE PRIMARY KEY (SPACE_TYPE_ID)
);

-- Tabla: SPACE
CREATE TABLE SIGEU.SPACE (
    SPACE_ID      VARCHAR(2)  NOT NULL,
    NAME          VARCHAR(20) NOT NULL,
    CAPACITY      NUMBER      NOT NULL,
    SPACE_TYPE_ID VARCHAR(2),
    BUILDING_ID   VARCHAR(2),
    CONSTRAINT PK_SPACE_ID PRIMARY KEY (SPACE_ID),
    CONSTRAINT FK_SPACE_TYPE FOREIGN KEY (SPACE_TYPE_ID)
        REFERENCES SIGEU.SPACE_TYPE (SPACE_TYPE_ID),
    CONSTRAINT FK_SPACE_BUILDING FOREIGN KEY (BUILDING_ID)
        REFERENCES SIGEU.BUILDING (BUILDING_ID)
);

-- Tabla: RESERVATION
CREATE TABLE SIGEU.RESERVATION (
    RESERVATION_NUMBER  VARCHAR(2) NOT NULL,
    DATE                TIMESTAMP,
    CODE                VARCHAR(10),
    CONSTRAINT PK_RESERVATION_NUMBER PRIMARY KEY (RESERVATION_NUMBER),
    CONSTRAINT FK_CODE_USER FOREIGN KEY (CODE)
        REFERENCES SIGEU.USER (CODE)
);

-- Tabla: RESERVATION_DETAIL
CREATE TABLE SIGEU.RESERVATION_DETAIL (
    LINE_NUMBER         NUMERIC    NOT NULL,
    START_TIME          TIMESTAMP  NOT NULL,
    END_TIME            TIMESTAMP  NOT NULL,
    STATUS              CHAR(1)    NOT NULL,
    RESERVATION_NUMBER  VARCHAR(2) NOT NULL,
    SPACE_ID            VARCHAR(2) NOT NULL,
    CONSTRAINT PK_LINE_NUMBER PRIMARY KEY (LINE_NUMBER, RESERVATION_NUMBER),
    CONSTRAINT FK_RESERVATION_NUM FOREIGN KEY (RESERVATION_NUMBER)
        REFERENCES SIGEU.RESERVATION (RESERVATION_NUMBER),
    CONSTRAINT FK_SPACE_ID FOREIGN KEY (SPACE_ID)
        REFERENCES SIGEU.SPACE (SPACE_ID),
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('A', 'C', 'P'))
);
